### ISSUE TITLE
 No picture

### ISSUE THREAD

**Issue by wuyuwangqingtian** [tenfoldpaper/yolov5_ros#2]
After running roslaunch yolov5_launch.launch, why doesn't the detection screen appear? What should I do if the detection screen appears

**Comment by tenfoldpaper** [comment]
There's no code for visualising the detection on-the-go. The detections are saved to a folder that can be enabled with the right option (--save-img, --nosave = false, iirc). You will have to write the live visualisation part yourself.

**Comment by wuyuwangqingtian** [comment]
thank you for your reply
